# Generated by Django 3.2.12 on 2022-09-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenericView1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.AddField(
            model_name='student',
            name='Description',
            field=models.TextField(default='desc1'),
        ),
        migrations.AddField(
            model_name='student',
            name='Title',
            field=models.CharField(default='Book1', max_length=20),
        ),
    ]
